const today = new Date();
const state = { anchor: new Date(today.getFullYear(), today.getMonth(), 1), village: 'all' };
function wireNav(){ document.querySelectorAll('.nav-row [data-action]').forEach(b=>{ b.addEventListener('click',()=>{ const a=b.dataset.action; if(a==='prev') state.anchor=new Date(state.anchor.getFullYear(), state.anchor.getMonth()-1,1); if(a==='next') state.anchor=new Date(state.anchor.getFullYear(), state.anchor.getMonth()+1,1); if(a==='today') state.anchor=new Date(today.getFullYear(), today.getMonth(),1); renderNineColumns(); }); }); }
function wireParams(){ const v=document.getElementById('param-village'); if(v) v.addEventListener('change',e=>{ state.village=e.target.value; renderNineColumns(); }); }
function daysInMonth(y,m){ return new Date(y,m+1,0).getDate(); }
function isSameDay(a,b){ return a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth()&&a.getDate()===b.getDate(); }
function formatDayLabel(d){ const wd=new Intl.DateTimeFormat('fr-FR',{weekday:'short'}).format(d); const dm=new Intl.DateTimeFormat('fr-FR').format(d); return `${wd} – ${dm}`; }
function computeTraditionalLabel(d,village){ return `Trad • ${village==='all'?'Général':village}`; }
function monthLabel(y,m){ return new Intl.DateTimeFormat('fr-FR',{month:'long',year:'numeric'}).format(new Date(y,m,1)); }
function renderNineColumns(){ const root=document.getElementById('calendar-9cols'); root.setAttribute('aria-busy','true'); root.innerHTML=''; const months=[ new Date(state.anchor.getFullYear(), state.anchor.getMonth()-1,1), new Date(state.anchor.getFullYear(), state.anchor.getMonth(),1), new Date(state.anchor.getFullYear(), state.anchor.getMonth()+1,1) ]; months.forEach(start=>renderOneMonth(root,start,state.village)); root.setAttribute('aria-busy','false'); }
function renderOneMonth(root,startOfMonth,village){ const y=startOfMonth.getFullYear(); const m=startOfMonth.getMonth(); const nDays=daysInMonth(y,m); const wrap=document.createElement('div'); wrap.className='month'; wrap.setAttribute('aria-label', monthLabel(y,m)); const header=document.createElement('div'); header.className='month-header'; header.textContent=monthLabel(y,m); wrap.appendChild(header); const hDate=document.createElement('div'); hDate.className='cell col-title'; hDate.textContent='Date'; wrap.appendChild(hDate); const hGreg=document.createElement('div'); hGreg.className='cell col-title'; hGreg.textContent='Jour grégorien'; wrap.appendChild(hGreg); const hTrad=document.createElement('div'); hTrad.className='cell col-title'; hTrad.textContent='Jour traditionnel'; wrap.appendChild(hTrad); for(let d=1; d<=nDays; d++){ const cur=new Date(y,m,d); const cDate=document.createElement('div'); cDate.className='cell date'+(isSameDay(cur,today)?' today':''); cDate.textContent=String(d); wrap.appendChild(cDate); const cGreg=document.createElement('div'); cGreg.className='cell greg'; cGreg.textContent=formatDayLabel(cur); wrap.appendChild(cGreg); const cTrad=document.createElement('div'); cTrad.className='cell tradi'; cTrad.textContent=computeTraditionalLabel(cur,village); wrap.appendChild(cTrad); } root.appendChild(wrap); }
wireNav(); wireParams(); renderNineColumns();
